[package]
name = "pals-vm"
version = "0.0.1"
edition = "2021"
description = "Parallel Asynchronous Logic Simulator and Virtual Machine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pals-vm"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
async-channel = "1.8.0"
derive_more = "0.99.17"
nom = "7.1.3"
petgraph = "0.6.3"
rustc-hash = "1.1.0"
tokio = { version = "1.27.0", features = ["full"] }
