[package]
name = "pals-vm"
version = "0.0.1"
edition = "2021"
description = "Parallel Asynchronous Logic Simulator and Virtual Machine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pals-vm"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
async-recursion = "1.0.4"
console-subscriber = "0.1.8"
derive_more = "0.99.17"
# env_logger = "0.10.0"
# log = "0.4.17"
nom = "7.1.3"
petgraph = "0.6.3"
rustc-hash = "1.1.0"
tokio = { version = "1.27.0", features = ["full", "tracing"] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.7", features = ["futures-util"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
